MCU = STM32F401
BOARD = GENERIC_STM32_F401XC

# BOOTLOADER = stm32-dfu
BOOTLOADER = tinyuf2
FIRMWARE_FORMAT = uf2
UF2_FAMILY = 0xabcdf401
# MCU_LDSCRIPT = STM32F401xC

SERIAL_DRIVER = usart
UARTENABLE = yes

# OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
# OPT_DEFS += -DQMK_MCU_STM32F401
# OPT_DEFS += -DBOOTLOADER_TINYUF2
EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = legacy
